{
 "title": "AMG Data Plane E2E Performance Test",
 "time": { "from": "2022-03-11T09:42:13.513Z", "to": "2022-03-11T10:01:55.074Z" },
 "templating": {
  "list": [
   {
    "name": "workflow",
    "label": "workflow",
    "query": {
     "query": "label_values(k6_http_req_failed_count{}, workflow)"
    }
   }
  ]
 },
 "panels": [
  { "title": "K6 Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overall Request Success Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (k6_http_req_failed_count{group!=\"::setup\", expected_response=\"true\", workflow=~\"$workflow\"}) / sum (k6_http_req_failed_count{group!=\"::setup\", workflow=~\"$workflow\"})",
     "legendFormat": "request_success_rate"
    }
   ]
  },
  {
   "title": "Overall Request Fail Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (k6_http_req_failed_count{group!=\"::setup\", expected_response=\"false\", workflow=~\"$workflow\"}) / sum (k6_http_req_failed_count{group!=\"::setup\", workflow=~\"$workflow\"})",
     "legendFormat": "request_fail_rate"
    }
   ]
  },
  {
   "title": "Virtual Users (VUs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "k6_vus{workflow=~\"$workflow\"}",
     "legendFormat": "k6_vus_{{pod}}"
    },
    {
     "expr": "k6_vus_max{workflow=~\"$workflow\"}",
     "legendFormat": "k6_vus_max_{{pod}}"
    },
    {
     "expr": "sum (k6_vus{workflow=~\"$workflow\"})",
     "legendFormat": "total_vus"
    },
    {
     "expr": "k6_vu{workflow=~\"$workflow\"}"
    }
   ]
  },
  {
   "title": "Overall Average Failed Requests (1min window)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(k6_http_req_failed_sum{group!=\"::setup\", expected_response=\"false\", workflow=~\"$workflow\"}[1m])) / sum by (status) (rate(k6_http_req_failed_count{group!=\"::setup\", expected_response=\"false\", workflow=~\"$workflow\"}[1m]))",
     "legendFormat": "fail_rate_{{status}}"
    }
   ]
  },
  {
   "title": "Detailed HTTP Request Latency (1min window)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (status, url) (rate(k6_http_req_duration_sum{group!=\"::setup\", expected_response=\"true\", workflow=~\"$workflow\"}[1m]))\r\n/\r\nsum by (status, url) (rate(k6_http_req_duration_count{group!=\"::setup\", expected_response=\"true\", workflow=~\"$workflow\"}[1m]))",
     "legendFormat": "latency_{{status}}_{{url}}"
    },
    {
     "expr": "sum by (status, url) (rate(k6_http_req_duration_sum{group!=\"::setup\", expected_response=\"false\", workflow=~\"$workflow\"}[1m]))\r\n/\r\nsum by (status, url) (rate(k6_http_req_duration_count{group!=\"::setup\", expected_response=\"false\", workflow=~\"$workflow\"}[1m]))",
     "legendFormat": "latency_{{status}}_{{url}}"
    }
   ]
  },
  {
   "title": "RPS (1min window)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(k6_http_reqs{group!=\"::setup\", workflow=~\"$workflow\"}[1m]))",
     "legendFormat": "rps_{{pod}}"
    },
    {
     "expr": "sum (rate(k6_http_reqs{group!=\"::setup\", workflow=~\"$workflow\"}[1m]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Overall HTTP Request Latency (1min window)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum (rate(k6_http_req_duration_sum{group!=\"::setup\", workflow=~\"$workflow\"}[1m]))/sum (rate(k6_http_req_duration_count{group!=\"::setup\", workflow=~\"$workflow\"}[1m]))",
     "legendFormat": "overall_latency"
    }
   ]
  },
  {
   "title": "Max P90 HTTP Request Latency Among Runners",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max by (status) (k6_http_req_duration{group!=\"::setup\", expected_response=\"true\", quantile=\"0.9\", workflow=~\"$workflow\"})",
     "legendFormat": "p90_{{status}}"
    },
    {
     "expr": "max by (status) (k6_http_req_duration{group!=\"::setup\", expected_response=\"false\", quantile=\"0.9\", workflow=~\"$workflow\"})",
     "legendFormat": "p90_{{status}}"
    }
   ]
  },
  {
   "title": "Max P95 HTTP Request Latency Among Runners",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max by (status) (k6_http_req_duration{group!=\"::setup\", expected_response=\"true\", quantile=\"0.95\", workflow=~\"$workflow\"})",
     "legendFormat": "p95_{{status}}"
    },
    {
     "expr": "max by (status) (k6_http_req_duration{group!=\"::setup\", expected_response=\"false\", quantile=\"0.95\", workflow=~\"$workflow\"})",
     "legendFormat": "p95_{{status}}"
    }
   ]
  },
  {
   "title": "Iteration Per Second (1min Windows)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum (rate(k6_iterations{workflow=~\"$workflow\"}[1m]))",
     "legendFormat": "ips"
    }
   ]
  },
  {
   "title": "Dropped Interation Per Second (1min Window)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum (rate(k6_dropped_iterations{workflow=~\"$workflow\"}[1m]))",
     "legendFormat": "dips"
    }
   ]
  },
  {
   "title": "Overall Iteration Latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum (rate(k6_iteration_duration_sum{group!~\".*setup|teardown.*\", workflow=~\"$workflow\"}[1m])) /sum (rate(k6_iteration_duration_count{group!~\".*setup|teardown.*\", workflow=~\"$workflow\"}[1m]))",
     "legendFormat": "iteration_latency"
    }
   ]
  },
  {
   "title": "K6 Runner",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "K6 Runner CPU Requests and Limits",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\r\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\",\r\n    namespace=\"argo\", pod=~\"$workflow.*\", resource=\"cpu\", container=\"main\"}\r\n) by (pod, container)",
       "legendFormat": "{{pod}}_{{container}}_requests"
      },
      {
       "expr": "sum(\r\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\",\r\n    namespace=\"argo\", pod=~\"$workflow.*\", resource=\"cpu\", container=\"main\"}\r\n) by (pod, container)",
       "legendFormat": "{{pod}}_{{container}}_limits"
      }
     ]
    },
    {
     "title": "K6 Runner CPU Usage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"argo\", pod=~\"$workflow.*\", container=\"main\"}) by (pod, container)",
       "legendFormat": "{{pod}}_{{container}}"
      },
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"argo\", pod=~\"$workflow.*\", container=\"main\"}[1m])) by (pod, container) /sum(increase(container_cpu_cfs_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"argo\", pod=~\"$workflow.*\", container=\"main\"}[1m])) by (pod, container)",
       "legendFormat": "{{pod}}_{{container}}_throttled_1min_window"
      }
     ]
    },
    {
     "title": "K6 Runner Memory Requests and Limits",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(\r\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"argo\", pod=~\"$workflow.*\", resource=\"memory\", container=\"main\"}\r\n) by (pod, container)",
       "legendFormat": "{{pod}}_{{container}}_requests"
      }
     ]
    },
    {
     "title": "K6 Runner Memory Usage (WSS)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"argo\", pod=~\"$workflow.*\", container=\"main\", image!=\"\"}) by (pod, container)",
       "legendFormat": "{{pod}}_{{container}}"
      }
     ]
    },
    {
     "title": "K6 Runner Bandwidth (1min Window)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"argo\", pod=~\"$workflow.*\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}_receive"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"argo\", pod=~\"$workflow.*\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}_transmit"
      }
     ]
    }
   ]
  },
  { "title": "WUS2 Gateway Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Gateway Pod CPU Requests and Limits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\r\n    kube_pod_container_resource_requests{namespace=\"default\", pod=~\"app-rel-dp-gateway-([a-zA-Z0-9]+)-[a-zA-Z0-9]+\", resource=\"cpu\", container!~\"^(POD|)$\"}\r\n) by (pod, container)",
     "legendFormat": "{{pod}}_{{container}}_request"
    },
    {
     "expr": "sum(\r\n    kube_pod_container_resource_limits{namespace=\"default\", pod=~\"app-rel-dp-gateway-([a-zA-Z0-9]+)-[a-zA-Z0-9]+\", resource=\"cpu\", container!~\"^(POD|)$\"}\r\n) by (pod, container)",
     "legendFormat": "{{pod}}_{{container}}_limits"
    }
   ]
  },
  {
   "title": "Gateway Pod CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"default\", pod=~\"app-rel-dp-gateway-([a-zA-Z0-9]+)-[a-zA-Z0-9]+\", container!~\"^(POD|)$\"}) by (pod, container) ",
     "legendFormat": "{{pod}}_{{container}}"
    },
    {}
   ]
  },
  {
   "title": "Gateway Pod Memory Requests and Limits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(\r\n    kube_pod_container_resource_requests{namespace=\"default\", pod=~\"app-rel-dp-gateway-([a-zA-Z0-9]+)-[a-zA-Z0-9]+\", resource=\"memory\", container!~\"^(POD|)$\"}\r\n) by (pod, container)",
     "legendFormat": "{{pod}}_{{container}}_requests"
    },
    {
     "expr": "sum(\r\n    kube_pod_container_resource_limits{namespace=\"default\", pod=~\"app-rel-dp-gateway-([a-zA-Z0-9]+)-[a-zA-Z0-9]+\", resource=\"memory\", container!~\"^(POD|)$\"}\r\n) by (pod, container)",
     "legendFormat": "{{pod}}_{{container}}_limits"
    }
   ]
  },
  {
   "title": "Gateway Pod Memory Usage (WSS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{metrics_path=\"/metrics/cadvisor\", namespace=\"default\", pod=~\"app-rel-dp-gateway-([a-zA-Z0-9]+)-[a-zA-Z0-9]+\", container!~\"^(POD|)$\", image!=\"\"}) by (pod, container)",
     "legendFormat": "{{pod}}_{{container}}"
    }
   ]
  },
  {
   "title": "Gateway Pod Bandwidth (1min Window)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{metrics_path=\"/metrics/cadvisor\", namespace=\"default\", pod=~\"app-rel-dp-gateway-([a-zA-Z0-9]+)-[a-zA-Z0-9]+\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}_receive"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{metrics_path=\"/metrics/cadvisor\", namespace=\"default\", pod=~\"app-rel-dp-gateway-([a-zA-Z0-9]+)-[a-zA-Z0-9]+\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}_transmit"
    }
   ]
  }
 ]
}